apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobjectqueue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queuescaledeploy
  pollingInterval: 5                                # Optional. Default: 30 seconds
  cooldownPeriod:  30                               # Optional. Default: 300 seconds
  minReplicaCount: 0                                 # Optional. Default: 0
  maxReplicaCount: 100                               # Optional. Default: 100
  triggers:
  - type: azure-queue
    metadata:
      queueName: akshelperqueue
      queueLength: '3'
      connectionFromEnv: STORAGE_CONNECTION
      accountName: akshelperstorage